### ISSUE TITLE
表現効果（music）

### ISSUE THREAD

**Issue by 175B005** [175B005/crass_festival#10]
- 効果音設定ＢＧＭ追加。

**Comment by 175B005** [comment]
勝手にどんどんつけて～。
一通りついたらcloseでおｋ

**Comment by hhdfgg** [comment]
スクリプトのStageSの中に配列でSEを追加したので、StageSのスクリプトがついているButtonそれぞれで設定できる。
スクリプトは追加したいところに"StageS_aud.PlayOneShot(StageS_SE[0]);"だけでよい。そして、それぞれで設定。
ちょっと言葉だとわかりずらいので、会った時に説明します。

**Comment by hhdfgg** [comment]
Playerの効果音のスクリプトの件を相談したい。
配列にしたら、少しはコード数が少なくなるけど、名前がわからなくなるリスクがある。ということ

**Comment by 175B005** [comment]
了解。とりあえずは
ＳＥ全任せだけど、
スクリプトやし、知っておきたい。あとで、よろろ(^ ω ^)/～♪
