### ISSUE TITLE
操作説明

### ISSUE THREAD

**Issue by 175B005** [175B005/crass_festival#20]
- タイトルテロップ？  
 - 物理でA4紙にイラストレーターとかで描く  
 - 各シーンの端にキー操作のインフォ。canvas

**Comment by hhdfgg** [comment]
Stage1に操作説明を追加したど、文字だけにしたので、画像画像よいなら、画像にします。
あと、Unityの標準フォント形式だど、WebGLの時に日本語は使えないよ。（要相談）

**Comment by tanakaedu** [comment]
- [Fontna. フォントな。](http://www.fontna.com/)
- [ゲームに使えるフォント](http://wikinavi.net/vipgamecreator/index.php?%E3%82%B2%E3%83%BC%E3%83%A0%E3%81%AB%E4%BD%BF%E3%81%88%E3%82%8B%E3%83%95%E3%82%A9%E3%83%B3%E3%83%88)
- [FONT BEAR.NET 商用OKなフリーフォントを検索](https://fontbear.net/)

標準フォントはかっこ悪いので、この辺りからよきフォントを探してみてください。FONT BEARは癖のあるのが多いので、フォントな。やwikiから探すとよいです。

タイトルの一部とか、別シーンとかで、ライセンス情報を表示するシーンがあると楽かと。

**Comment by hhdfgg** [comment]
タイトルは書いた。
がA4のほうにそれを持っていこうとするとRBGで作っちゃったし、解像度７２だから、印刷用にCMYKに変えて、解像度も変えないといけない気がする。どっかで、そのようなことを聞いたような覚えがある。

**Comment by hhdfgg** [comment]
あと、忘れてたけど、タイトルの文字なしの絵もあるよ
