### ISSUE TITLE
ステージ構成

### ISSUE THREAD

**Issue by 175B005** [175B005/crass_festival#9]
- ポスステージ、（広場or塔）３Ｄ  
 - ギミック改善

**Comment by 175B005** [comment]
ギミックの話（お願い）
sideview移動床、落ちたら死ぬ。
ここはsideで見なきゃいけないところと、
mainで見ないと幅がないものと二種。

**Comment by 175B005** [comment]
- [説明用画像](https://github.com/175B005/crass_festival/blob/master/%E7%84%A1%E9%A1%8C.jpg)  
 - [説明２](https://github.com/175B005/crass_festival/blob/master/%E7%84%A1%E9%A1%8C1.jpg)  
 - [説明３](https://github.com/175B005/crass_festival/blob/master/%EF%BC%92%E7%84%A1%E9%A1%8C.jpg)

**Comment by 175B005** [comment]
bossStageは塔みたいに上がっていきます
階段で、外側をぐるぐるします。
イメージは螺旋階段の大きいやつ。

**Comment by 175B005** [comment]
追加のお願い
groundなどオブジェクトは
今あるものと同じコンポーネントを持たせてください。
あと、地面もろもろ物体である物は、重さを１００００でお願いします。

**Comment by tanakaedu** [comment]
重さの設定が、キャラクターとぶつかった時に動くのをとめるのが目的の場合は、重さではなく、以下で設定します。

- 静止物の場合・・・Rigidbodyはアタッチせず、staticにチェックを入れる
- 動くものの場合・・・Rigidbodyをつけた上で、ColliderのIsKinematicにチェックを入れる。ただし、他のオブジェクトへ物理的な影響を与えられなくなるので、他の方法が必要になる場合があるので要相談

**Comment by 175B005** [comment]
塔はなしで、
メインステージのおぶじぇくとは
staticでお願いします。rigはイランです・

**Comment by 175B005** [comment]
作業は遅れていましたが、
昨日にはこっちにコラボしてくれたので
良かったです。
closeしてっていったんだけど、
消さないから、俺が最終の編集したので、
それのcloseということで、、
